version: '3.8'

services:
  rucord:
    build: .
    ports:
      - "9001:3001"
    environment:
      - DB_HOST=62.173.148.71
      - DB_PORT=5432
      - DB_NAME=rucordbase
      - DB_USER=postgres
      - DB_PASSWORD=Alena71980324!
    restart: unless-stopped
